# Generated by Django 6.0.3 on 2026-04-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('text', models.TextField(null=True)),
                ('phone', models.CharField(max_length=15)),
                ('preferred_timing', models.TimeField()),
            ],
        ),
    ]
