# Generated by Django 6.0.3 on 2026-04-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_recordtype_record_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата заявки'),
        ),
        migrations.AlterField(
            model_name='record',
            name='preferred_timing',
            field=models.TimeField(verbose_name='удобное время звонка'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.recordtype', verbose_name='тип заявки'),
        ),
    ]
