# Generated by Django 6.0.3 on 2026-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_record_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=400)),
                ('attachment', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
    ]
